# Generated by Django 4.1.7 on 2023-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
    ]
