# Generated by Django 4.1.7 on 2023-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
