# Generated by Django 4.1.7 on 2023-05-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0004_invoice_invoice_detail_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_detail',
            name='Book',
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store_arboleda.cart'),
        ),
    ]
