# Generated by Django 4.1.7 on 2023-05-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0005_remove_invoice_detail_book_invoice_detail_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_detail',
            name='cart',
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store_arboleda.book'),
        ),
    ]
