# Generated by Django 4.1.7 on 2023-06-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0007_remove_book_author_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_copies', models.IntegerField(default=0)),
                ('copies_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='copies_in_stock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store_arboleda.stock'),
        ),
    ]
