# Generated by Django 4.1.7 on 2023-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0008_stock_remove_book_copies_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_store_arboleda.book'),
        ),
    ]
