# Generated by Django 4.1.7 on 2023-06-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0012_remove_invoice_user_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status_revision',
        ),
    ]
