# Generated by Django 4.1.7 on 2023-06-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_arboleda', '0014_inventory_invoice_detail_amount_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_detail',
            old_name='Book',
            new_name='book',
        ),
    ]
